import subprocess

subprocess.call("pip install discord", shell=True)
subprocess.call("pip install pyfiglet", shell=True)
subprocess.call("pip install requests", shell=True)
subprocess.call("pip install colorama", shell=True)
subprocess.call("pip install unicode", shell=True)
subprocess.call("pip install discord.utils", shell=True)
subprocess.call("pip install random", shell=True)
subprocess.call("pip install aiohttp", shell=True)
subprocess.call("pip install platform", shell=True)
subprocess.call("pip install text2art", shell=True)
subprocess.call("pip install asyncio", shell=True)
subprocess.call("pip install numpy", shell=True)
subprocess.call("pip install pypresence", shell=True)
subprocess.call("pip install plyer", shell=True)
subprocess.call("pip install colorful", shell=True)
subprocess.call("pip install dnspython", shell=True)
subprocess.call("pip install colored", shell=True)
subprocess.call("pip install wget", shell=True)
subprocess.call("pip install zipfile", shell=True)
subprocess.call("pip install shutil", shell=True)